/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2023-07-23 13:30:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<style>\n");
      out.write("#landing-header {\n");
      out.write("    z-index: 1;\n");
      out.write("    position: relative;\n");
      out.write("    text-align: center;\n");
      out.write("    padding-top: 40vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slideshow {\n");
      out.write("    position: fixed;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    z-index: 0;\n");
      out.write("    list-style: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slideshow li {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("    position: absolute;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    background-size: cover;\n");
      out.write("    background-position: 50% 50%;\n");
      out.write("    background-repeat: no-repeat;\n");
      out.write("    opacity: 0;\n");
      out.write("    z-index: 0;\n");
      out.write("    animation: imageAnimation 50s linear infinite;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slideshow li:nth-child(1) {\n");
      out.write("    background-image: url(https://www.ccn.com/wp-content/uploads/2017/09/listhotel-buriram.jpg)\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slideshow li:nth-child(2) {\n");
      out.write("    background-image: url(https://www.ccn.com/wp-content/uploads/2017/09/listhotel-buriram.jpg);\n");
      out.write("    animation-delay: 10s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slideshow li:nth-child(3) {\n");
      out.write("    background-image: url(https://media-cdn.tripadvisor.com/media/photo-s/12/e2/82/62/harris-vertu-hotel-harmoni.jpg);\n");
      out.write("    animation-delay: 20s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slideshow li:nth-child(4) {\n");
      out.write("    background-image: url(https://media-cdn.tripadvisor.com/media/photo-s/12/e2/82/62/harris-vertu-hotel-harmoni.jpg);\n");
      out.write("    animation-delay: 30s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slideshow li:nth-child(5) {\n");
      out.write("    background-image: url(http://i.imgur.com/TVGe0Ef.jpg);\n");
      out.write("    animation-delay: 40s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes imageAnimation {\n");
      out.write("    0% {\n");
      out.write("        opacity: 0;\n");
      out.write("        animation-timing-function: ease-in;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    10% {\n");
      out.write("        opacity: 1;\n");
      out.write("        animation-timing-function: ease-out;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    20% {\n");
      out.write("        opacity: 1\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    30% {\n");
      out.write("        opacity: 0\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write(".no-cssanimations .slideshow li {\n");
      out.write("    opacity: 1;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div id=\"landing-header\">\n");
      out.write("		<h1>Welcome to Hotels!</h1>\n");
      out.write("		<a href=\"/myapp/hotels\" class=\"btn btn-lg btn-success\">View All\n");
      out.write("			Hotels</a>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<ul class=\"slideshow\">\n");
      out.write("		<li></li>\n");
      out.write("		<li></li>\n");
      out.write("		<li></li>\n");
      out.write("		<li></li>\n");
      out.write("		<li></li>\n");
      out.write("	</ul>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
